// Generated by gencpp from file slam_robot/AddTwoInts.msg
// DO NOT EDIT!


#ifndef SLAM_ROBOT_MESSAGE_ADDTWOINTS_H
#define SLAM_ROBOT_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <slam_robot/AddTwoIntsRequest.h>
#include <slam_robot/AddTwoIntsResponse.h>


namespace slam_robot
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace slam_robot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::slam_robot::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::slam_robot::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::slam_robot::AddTwoInts > {
  static const char* value()
  {
    return "slam_robot/AddTwoInts";
  }

  static const char* value(const ::slam_robot::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::slam_robot::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::slam_robot::AddTwoInts > 
template<>
struct MD5Sum< ::slam_robot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::slam_robot::AddTwoInts >::value();
  }
  static const char* value(const ::slam_robot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_robot::AddTwoIntsRequest> should match 
// service_traits::DataType< ::slam_robot::AddTwoInts > 
template<>
struct DataType< ::slam_robot::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::slam_robot::AddTwoInts >::value();
  }
  static const char* value(const ::slam_robot::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::slam_robot::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::slam_robot::AddTwoInts > 
template<>
struct MD5Sum< ::slam_robot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::slam_robot::AddTwoInts >::value();
  }
  static const char* value(const ::slam_robot::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::slam_robot::AddTwoIntsResponse> should match 
// service_traits::DataType< ::slam_robot::AddTwoInts > 
template<>
struct DataType< ::slam_robot::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::slam_robot::AddTwoInts >::value();
  }
  static const char* value(const ::slam_robot::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SLAM_ROBOT_MESSAGE_ADDTWOINTS_H
